### ISSUE TITLE
Incorrect link under prerequisites  

### ISSUE THREAD

**Issue by CookieSource** [ODEX-TOS/tos-desktop-environment#117]
Hi the link in the readme  prerequisites  https://github.com/ODEX-TOS/tos-live/blob/master/repo/BUILD/PKGBUILD_AWESOME doesn't lead anywhere

**Comment by F0xedb** [comment]
Fixed in 27bdc215261c9ef5eec425f206d231a55e98a1b1

**Comment by F0xedb** [comment]
The correct link should have been:
https://github.com/ODEX-TOS/tos-desktop-environment/blob/f3a4cbbc74c40268a771947bea0044a9f70d730f/build-utils/PKGBUILD#L30-L37
