### ISSUE TITLE
The icon "wireless network is disconnected" shows on the desktop topbar. Can you remove this please?

### ISSUE THREAD

**Issue by RazeSevi** [ODEX-TOS/tos-desktop-environment#118]
**Describe the bug**
The network icon "Wireless network" is still showing even if you're connected with LAN cable.

**To Reproduce**
1. Go to 'Your a computer without wi-fi'
2. check the top-bar and see if there's a wi-fi icon.
3. See error

**Expected behavior**
Remove this icon if you're not connected to wi-fi 

**Screenshots**
![image](https://user-images.githubusercontent.com/67441918/124979560-7c66d500-e033-11eb-8d8e-76eb6f925f5b.png)

**Desktop (please complete the following information):**
 - OS: [TOS]
 - Version [TDE v0.8.11080 (Beta)]

**Comment by F0xedb** [comment]
Is fixed in c85a6e2100644a2c1d775a4d47bce95894b6fea4
